apiVersion: batch/v1
kind: CronJob
metadata:
  name: cornjob-example
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3 #The number of successful jobs to retain.
  failedJobsHistoryLimit: 1 #The number of failed jobs to retain.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            args: ["echo hello from $HOSTNAME!"]
          restartPolicy: OnFailure
