apiVersion: batch/v1
kind: Job
metadata:
  name: get-hostname
  #namespace: default
spec:
  template:
    spec:
      containers:
      - name: hostname
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["echo hello from $HOSTNAME!"]
      backoffLimit: 4
      completions: 4
      parallelism: 2
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
